/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.NilaiController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author nothing
 */
public class FormInputNilai extends javax.swing.JFrame {

    NilaiController nilaiC;

    /**
     * Creates new form FormInputNilai
     */
    public FormInputNilai() {
        nilaiC = new NilaiController(this);
        initComponents();
        nilaiC.showDataMhs();
        nilaiC.showDataNilai();
    }

    public JTextField getTxt_Nuas() {
        return txt_Nuas;
    }

    public JTextField getTxt_Nuts() {
        return txt_Nuts;
    }

    public JTextField getTxt_mk() {
        return txt_mk;
    }

    public JTextField getTxt_semester() {
        return txt_semester;
    }

    public JTextField getTxt_sks() {
        return txt_sks;
    }

    public JTable getTblMhs() {
        return tblMhs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMhs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_idMhs = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_namaMhs = new javax.swing.JTextField();
        cmb_jk = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btn_simpanMhs = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_mk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_sks = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_semester = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Nuts = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Nuas = new javax.swing.JTextField();
        btn_simpanNilai = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btn_updateMhs = new javax.swing.JButton();
        btn_updateNilai = new javax.swing.JButton();
        btn_resetNilai = new javax.swing.JButton();
        btn_hapusNilai = new javax.swing.JButton();
        btn_hapusMhs = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMhs);

        jLabel1.setText("DATA MAHASISWA");

        jLabel2.setText("ID Mahasiswa");

        jLabel3.setText("Nama");

        txt_namaMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaMhsActionPerformed(evt);
            }
        });

        cmb_jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));

        jLabel4.setText("Jenis Kelamin");

        btn_simpanMhs.setText("Simpan Data Baru");
        btn_simpanMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanMhsActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel5.setText("TAMBAH MAHASISWA");

        jLabel6.setText("FORM INPUT NILAI (PILIH DATA MAHASISWA TERLEBIH DAHULU)");

        jLabel7.setText("Nama Mata Kuliah");

        txt_mk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mkActionPerformed(evt);
            }
        });

        jLabel8.setText("Sks");

        txt_sks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sksActionPerformed(evt);
            }
        });

        jLabel9.setText("Semester");

        txt_semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_semesterActionPerformed(evt);
            }
        });

        jLabel10.setText("Nilai UTS");

        txt_Nuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NutsActionPerformed(evt);
            }
        });

        jLabel11.setText("Nilai UAS");

        txt_Nuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NuasActionPerformed(evt);
            }
        });

        btn_simpanNilai.setText("Tambah Data Nilai");
        btn_simpanNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanNilaiActionPerformed(evt);
            }
        });

        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNilaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNilai);

        jLabel12.setText("DATA NILAI MAHASISWA");

        btn_updateMhs.setText("Update Data Mahasiswa");
        btn_updateMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateMhsActionPerformed(evt);
            }
        });

        btn_updateNilai.setText("Update Data Nilai");
        btn_updateNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateNilaiActionPerformed(evt);
            }
        });

        btn_resetNilai.setText("Reset");
        btn_resetNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetNilaiActionPerformed(evt);
            }
        });

        btn_hapusNilai.setText("Hapus Nilai");
        btn_hapusNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusNilaiActionPerformed(evt);
            }
        });

        btn_hapusMhs.setText("Hapus Mahasiswa");
        btn_hapusMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusMhsActionPerformed(evt);
            }
        });

        btn_logout.setText("Log out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_logout)
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_namaMhs, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_idMhs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(cmb_jk, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_simpanMhs)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_reset))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(btn_updateMhs))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_hapusMhs))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_sks, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(235, 235, 235)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txt_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Nuts, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11)
                                            .addComponent(txt_Nuas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_resetNilai)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_hapusNilai))
                                            .addComponent(btn_updateNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_simpanNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(txt_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(593, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_logout)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_idMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_jk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_simpanMhs)
                                .addComponent(btn_reset)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_namaMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_updateMhs)
                                .addComponent(btn_hapusMhs))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Nuas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_sks, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Nuts, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_simpanNilai))))
                        .addGap(18, 18, 18)
                        .addComponent(btn_updateNilai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_resetNilai)
                            .addComponent(btn_hapusNilai)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaMhsActionPerformed

    public JTable getTblNilai() {
        return tblNilai;
    }


    private void btn_simpanMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanMhsActionPerformed
        nilaiC.insertMhs();
        nilaiC.showDataMhs();
    }//GEN-LAST:event_btn_simpanMhsActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        nilaiC.resetForm();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tblMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMhsMouseClicked
        // TODO add your handling code here:
        nilaiC.clickDataTableMhs(tblMhs.getSelectedRow());
    }//GEN-LAST:event_tblMhsMouseClicked

    private void txt_mkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mkActionPerformed

    private void txt_sksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sksActionPerformed

    private void txt_semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_semesterActionPerformed

    private void txt_NutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NutsActionPerformed

    private void txt_NuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NuasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NuasActionPerformed

    private void btn_simpanNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanNilaiActionPerformed
        nilaiC.insertNilai();
        nilaiC.showDataNilai();
    }//GEN-LAST:event_btn_simpanNilaiActionPerformed

    private void btn_updateMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateMhsActionPerformed
        nilaiC.updateMhs();
        nilaiC.showDataMhs();
    }//GEN-LAST:event_btn_updateMhsActionPerformed

    private void tblNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNilaiMouseClicked
        nilaiC.clickDataTableNilai(tblNilai.getSelectedRow());

    }//GEN-LAST:event_tblNilaiMouseClicked

    private void btn_resetNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetNilaiActionPerformed
        nilaiC.resetForm();
    }//GEN-LAST:event_btn_resetNilaiActionPerformed

    private void btn_updateNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateNilaiActionPerformed
        nilaiC.updateNilai();
        nilaiC.showDataNilai();
    }//GEN-LAST:event_btn_updateNilaiActionPerformed

    private void btn_hapusMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusMhsActionPerformed
       nilaiC.deleteMhs();
       nilaiC.showDataMhs();
    }//GEN-LAST:event_btn_hapusMhsActionPerformed

    private void btn_hapusNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusNilaiActionPerformed
        nilaiC.deleteNilai();
        nilaiC.showDataNilai();
    }//GEN-LAST:event_btn_hapusNilaiActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInputNilai().setVisible(true);
            }
        });
    }

    public JButton getBtn_reset() {
        return btn_reset;
    }

    public JButton getBtn_simpanMhs() {
        return btn_simpanMhs;
    }

    public JComboBox<String> getCmb_jk() {
        return cmb_jk;
    }

    public JTextField getTxt_idMhs() {
        return txt_idMhs;
    }

    public JTextField getTxt_namaMhs() {
        return txt_namaMhs;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapusMhs;
    private javax.swing.JButton btn_hapusNilai;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_resetNilai;
    private javax.swing.JButton btn_simpanMhs;
    private javax.swing.JButton btn_simpanNilai;
    private javax.swing.JButton btn_updateMhs;
    private javax.swing.JButton btn_updateNilai;
    private javax.swing.JComboBox<String> cmb_jk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMhs;
    private javax.swing.JTable tblNilai;
    private javax.swing.JTextField txt_Nuas;
    private javax.swing.JTextField txt_Nuts;
    private javax.swing.JTextField txt_idMhs;
    private javax.swing.JTextField txt_mk;
    private javax.swing.JTextField txt_namaMhs;
    private javax.swing.JTextField txt_semester;
    private javax.swing.JTextField txt_sks;
    // End of variables declaration//GEN-END:variables
}
